= Spring-Boot CXF JAXRS Keycloak QuickStart

This example demonstrates how you can use Apache CXF JAXRS with is secured by Keycloak with Spring Boot.

The quickstart uses Spring Boot to configure a little application that includes a CXF JAXRS endpoint with Swagger enabled, which is secured by Keycloak.

IMPORTANT: This quickstart can run in 1 modes: standalone on your machine.

== Deployment options

You can run this quickstart in the following modes:

* Standalone on your machine


== Running the quickstart standalone on your machine

To run this quickstart as a standalone project on your local machine:

. Download the project and extract the archive on your local filesystem.
. Build the project:
+
[source,bash,options="nowrap",subs="attributes+"]
----
$ cd PROJECT_DIR
$ mvn clean package
----
. Run the service:

+
[source,bash,options="nowrap",subs="attributes+"]
----
$ mvn spring-boot:run
----

You can then access the CXF JAXRS endpoint directly from your Web browser, e.g.:

- <http://localhost:8080/services/helloservice/sayHello/FIS>
will display "Hello FIS, Welcome to CXF RS Spring Boot World!!!"
